development:
  adapter: postgresql
  encoding: unicode
  database: traininged_development
  pool: 5
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: traininged_test
  pool: 5
  password:
